### ISSUE TITLE
Request for support

### ISSUE THREAD

**Issue by Mathula** [LiliomLab/laravel-zoho-campaigns#2]
plugin is not working can you please update to support the new version

**Comment by mkwsra** [comment]
Do you mean Laravel/PHP related or from Zoho side? 

And for sure just tell me which and I will immediately update it 👍  thanks for reaching out

**Comment by Mathula** [comment]
Hi from Zoho side. I am trying to use this plugin in laravel 5.8 and display error on null value which means can you please update this to support for the zoho campaign API version 1.1

**Comment by mkwsra** [comment]
Hi Mathula,

Sorry but honestly I'm not planning to upgrade to ver 1.1 for now


However, I'm planning on updating the library soon and test it for v1.1

**Comment by Mathula** [comment]
So can you tell me how to get the version 1.0 access token

**Comment by mkwsra** [comment]
For sure

[https://www.zoho.com/campaigns/help/developers/authentication-token.html](https://www.zoho.com/campaigns/help/developers/authentication-token.html)

Check out this section "Generate Authentication Token"

**Comment by Mathula** [comment]
Null value is return when I use this

**Comment by mkwsra** [comment]
Sorry, but I cannot help you when you write to me "Null value" I've to understand where.

Is the output of `\Campaigns::testCredentials();` is right to you?

**Comment by Mathula** [comment]
I got this error message 
"Return value of Liliom\Zoho\Campaigns\CampaignsClient::getMailingLists() must be an object, null returned"  for \Campaigns::getMailingLists();
and for \Campaigns::testCredentials(); the API token  is displaying do you want that token  value?

**Comment by mkwsra** [comment]
No, I don't need the token.

If you're sure that you've mailing lists within your account, then sorry but this is obviously an issue, I will investigate **later about this and get back to you**

**Comment by Mathula** [comment]
ok thank you
